/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // dataverse-simulate
    {
      type: 'category',
      label: 'dataverse-simulate',
      link: {
        type: "doc",
        id: 'dataverse-simulate/intro'
      },
      items: [
        'dataverse-simulate/mocking-for-the-organization-service',
        'dataverse-simulate/mocking-for-plugins',
        // simulator-options
        {
          type: 'category',
          label: 'Simulator options',
          link: {
            type: "doc",
            id: 'dataverse-simulate/simulator-options/simulator-options'
          },
          items: [
            'dataverse-simulate/simulator-options/setting-system-time',
            'dataverse-simulate/simulator-options/setting-authenticated-user',
            'dataverse-simulate/simulator-options/setting-entity-processors',
            'dataverse-simulate/simulator-options/setting-plugin-context',
            'dataverse-simulate/simulator-options/faking-service-failures'
          ]
        },
        // data-stores
        {
          type: 'category',
          label: 'Data stores',
          link: {
            type: "doc",
            id: 'dataverse-simulate/data-stores/data-stores'
          },
          items: [
            {
              type: 'category',
              label: 'Entity data',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/entity-data/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/entity-data',
                }
              ]
            },
            {
              type: 'category',
              label: 'Plugin traces',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/plugin-traces/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/plugin-traces',
                }
              ]
            },
            {
              type: 'category',
              label: 'Application telemetry',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/application-telemetry/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/application-telemetry',
                }
              ]
            },
            {
              type: 'category',
              label: 'Simulator audits',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/simulator-audits/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/simulator-audits',
                }
              ]
            },
          ]
        },
        // entity-processors
        {
          type: 'category',
          label: 'Entity processors',
          link: {
            type: "doc",
            id: 'dataverse-simulate/entity-processors/entity-processors'
          },
          items: [
            'dataverse-simulate/entity-processors/create',
            'dataverse-simulate/entity-processors/update'
          ],
        },
        'dataverse-simulate/supported-sdk-messages',
        // release-notes
        {
          type: 'category',
          label: 'Release notes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'dataverse-simulate/release-notes',
            }
          ],
        }
      ],
    },
    // markdown-maker
    {
      type: 'category',
      label: 'markdown-maker',
      link: {
        type: "doc",
        id: 'markdown-maker/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cds-customisation', // Specify the directory where your docs are
        }
      ]
    },
    // cds-customisation
    {
      type: 'category',
      label: 'cds-customisation',
      link: {
        type: "doc",
        id: 'cds-customisation/intro'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cds-customisation',
        }
      ]
    },
    // break
    {
      type: "html",
      value: "<hr/>"
    },
    // style-guide
    {
      type: 'category',
      label: 'Style guide',
      link: {
        type: "doc",
        id: 'style-guide/intro'
      },
      items: [
        // Repos and code standards
        {
          type: 'category',
          label: 'Repo and code standards',
          link: {
            type: "doc",
            id: 'dataverse-simulate/simulator-options/simulator-options'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cds-customisation',
            }
          ]
        },
        // Agile and devops
        {
          type: 'category',
          label: 'Agile and devops',
          link: {
            type: "doc",
            id: 'dataverse-simulate/simulator-options/simulator-options'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cds-customisation',
            }
          ]
        },
        // Platforms
        {
          type: 'category',
          label: 'Platform best practices',
          link: {
            type: "doc",
            id: 'dataverse-simulate/simulator-options/simulator-options'
          },
          items: [
            // Power Pages
            {
              type: 'category',
              label: 'Power pages',
              link: {
                type: "doc",
                id: 'dataverse-simulate/simulator-options/simulator-options'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cds-customisation',
                }
              ]
            },
            // Azure
            {
              type: 'category',
              label: 'Azure',
              link: {
                type: "doc",
                id: 'dataverse-simulate/simulator-options/simulator-options'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cds-customisation',
                }
              ]
            },
          ]
        },
      ]
    },
  ],
};

module.exports = sidebars;
