/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // dataverse-simulate
    {
      type: 'category',
      label: 'dataverse-simulate',
      link: {
        type: "doc",
        id: 'dataverse-simulate/index'
      },
      items: [
        'dataverse-simulate/mocking-for-the-organization-service',
        'dataverse-simulate/mocking-for-plugins',
        // simulator-options
        {
          type: 'category',
          label: 'Simulator options',
          link: {
            type: "doc",
            id: 'dataverse-simulate/simulator-options/simulator-options'
          },
          items: [
            'dataverse-simulate/simulator-options/initialise-data',
            'dataverse-simulate/simulator-options/setting-system-time',
            'dataverse-simulate/simulator-options/setting-authenticated-user',
            'dataverse-simulate/simulator-options/setting-entity-processors',
            'dataverse-simulate/simulator-options/setting-plugin-context',
            'dataverse-simulate/simulator-options/faking-service-failures'
          ]
        },
        // data-stores
        {
          type: 'category',
          label: 'Data stores',
          link: {
            type: "doc",
            id: 'dataverse-simulate/data-stores/data-stores'
          },
          items: [
            {
              type: 'category',
              label: 'Entity data',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/entity-data/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/entity-data',
                }
              ]
            },
            {
              type: 'category',
              label: 'Plugin traces',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/plugin-traces/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/plugin-traces',
                }
              ]
            },
            {
              type: 'category',
              label: 'Application telemetry',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/application-telemetry/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/application-telemetry',
                }
              ]
            },
            {
              type: 'category',
              label: 'Simulator audits',
              link: {
                type: "doc",
                id: 'dataverse-simulate/data-stores/simulator-audits/intro'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'dataverse-simulate/data-stores/simulator-audits',
                }
              ]
            },
          ]
        },
        // entity-processors
        {
          type: 'category',
          label: 'Entity processors',
          link: {
            type: "doc",
            id: 'dataverse-simulate/entity-processors/entity-processors'
          },
          items: [
            'dataverse-simulate/entity-processors/create',
            'dataverse-simulate/entity-processors/update'
          ],
        },
        'dataverse-simulate/supported-sdk-messages',
        // release-notes
        {
          type: 'category',
          label: 'Release notes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'dataverse-simulate/release-notes',
            }
          ],
        }
      ],
    },
    // markdown-maker
    {
      type: 'category',
      label: 'markdown-maker',
      link: {
        type: "doc",
        id: 'markdown-maker/index'
      },
      items: [
        "markdown-maker/document-and-document-sets",
        "markdown-maker/content-types",
        {
          type: 'category',
          label: 'Document Parts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'markdown-maker/document-parts'
            }
          ],
        }
      ]
    },
    // cds-customisation
    {
      type: 'category',
      label: 'cds-customisation',
      link: {
        type: "doc",
        id: 'cds-customisation/index'
      },
      items: [
        "cds-customisation/plugin-registration",
        "cds-customisation/manifest-organisation-patterns",
        "cds-customisation/generate-customisation",
        "cds-customisation/migrate-bulk-deletion-jobs",
        "cds-customisation/toggle-process-activation",
        "cds-customisation/documentation-generator",
        "cds-customisation/portal-generation",
      ]
    },
    // portal-gds-accelerator
    {
      type: 'category',
      label: 'portal-gds-accelerator',
      link: {
        type: "doc",
        id: 'portal-gds-accelerator/index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'portal-gds-accelerator',
        }
      ]
    },
    // portal-test-framework
    {
      type: 'category',
      label: 'portal-test-framework',
      link: {
        type: "doc",
        id: 'portal-test-framework/index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'portal-test-framework',
        }
      ]
    },
    // gds-wireframe-stencils
    {
      type: 'category',
      label: 'gds-wireframe-stencils',
      link: {
        type: "doc",
        id: 'gds-wireframe-stencils/index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'gds-wireframe-stencils',
        }
      ]
    },
    // break
    {
      type: "html",
      value: "<hr/>"
    },
    // style-guide
    {
      type: 'category',
      label: 'Style guide',
      link: {
        type: "doc",
        id: 'style-guide/index'
      },
      items: [
        // Repos and code standards
        {
          type: 'category',
          label: 'Repo and code standards',
          link: {
            type: "doc",
            id: 'style-guide/repos/intro'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'style-guide/repos',
            }
          ]
        },
        // Agile and devops
        {
          type: 'category',
          label: 'Agile and devops',
          link: {
            type: "doc",
            id: 'style-guide/agile-and-devops/intro'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'style-guide/agile-and-devops',
            }
          ]
        },
        // Platforms
        {
          type: 'category',
          label: 'Platform best practices',
          link: {
            type: "doc",
            id: 'style-guide/platforms/intro'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'style-guide/platforms',
            }
          ]
        },
      ]
    },
  ],
};

module.exports = sidebars;
